[Trello 39] Follow existed user
real-social-media/frontend pull request #129
Opened 2020-10-12 08:26 UTC by omelniz

2020-10-15 00:19 UTC, azimgd commented
Contacts.getAll is already promise based, isn't it ?
https://github.com/real-social-media/frontend/blob/07154c1c39f8aedcff2bae598c8cc9218dd1e86f/src/store/ducks/contacts/saga/contactsGet.js#L27-L37

2020-10-15 01:32 UTC, azimgd requested changes

2020-10-15 01:32 UTC, azimgd commented on src/store/ducks/contacts/saga/contactsGet.js
> +      return { ...item, user: users[item.contactId] ? users[item.contactId].user : undefined }
`.map((item) => ({ ...item, user: path(item.contactId, 'user', users) }))` could also work

2020-10-15 01:32 UTC, azimgd commented on src/store/ducks/contacts/saga/contactsGet.js
>      yield put(actions.contactsGetFailure(errorWrapper(error)))
`yield put(actions.contactsGetFailure({ message: errorWrapper(error) }))` per convention

2020-10-15 01:32 UTC, azimgd commented on src/store/ducks/contacts/saga/contactsGet.js
> +    yield put(actions.contactsGetSuccess({ items: contacts }))
can we rename `items` -> `data` as we use this pattern in other sagas/reducers

2020-10-15 01:32 UTC, azimgd commented on src/store/ducks/contacts/saga/contactsGet.js
>      }
Can we move `throw new Error('Contacts permission is ${permission}')` error to the `requestContactsPermission` since i feel like it's more relevant there.

2020-10-15 01:32 UTC, azimgd commented on src/store/ducks/contacts/saga/contactsGet.js
> +    })
Wondering if following is equivalent to:
```
R.sortWith([
  R.ascend(R.prop('fullName')),
  R.ascend(R.prop('user'))
]);
```

2020-10-15 01:32 UTC, azimgd commented on src/components/InviteFriends/index.js
> +    const navigateProfile = navigationActions.navigateProfile(navigation, { userId: user.userId })
This will actually not work all the time. Will elaborate above at `ducks/contacts/queries.js` file

2020-10-15 01:32 UTC, azimgd commented on src/store/ducks/contacts/queries.js
> +          url64p
It's good that you only use limited amount of data here, but i suggest to use predefined user fragment because we would like to cache retrieved user into entities reducer in advance.
```
import * as usersList from 'store/ducks/users/queries/list'

....
findContacts() {
  contactId
  user {
    ...listUserFragment
  }
}
```

This way navigating from contacts page to profile page will be smoother since we already have basic data which is fetched with following selector. 
```
export const usersGetProfileSelector = (userId) => createDeepEqualSelector(
  [usersGetProfile(), entitiesSelector.entities],
  (usersGetProfile, entities) => {
    const user = userId || path(['data'])(usersGetProfile)
    const denormalized = normalizer.denormalizeUserGet(user, entities)
    return assocPath(['data'], denormalized)(usersGetProfile)
  },
)
```

To achieve this:
1. Change graphql query to fragment
2. Dispatch `entitiesActions.entitiesUsersMerge`

2020-10-15 01:34 UTC, azimgd commented
I also feel like we could decouple functions inside saga and component a bit more, components could be moved to their own files.

2020-10-15 01:34 UTC, azimgd commented
Good work

2020-10-15 12:13 UTC, omelniz commented on src/store/ducks/contacts/saga/index.js
> +import grandBonus from 'store/ducks/contacts/saga/grantBonus'
Renamed grandBonus to contactsGrantBonusRequest

2020-10-15 12:21 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
>      yield put(actions.contactsGetFailure(errorWrapper(error)))
Done

2020-10-15 12:24 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
> +    yield put(actions.contactsGetSuccess({ items: contacts }))
Done

2020-10-15 12:31 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
>      }
The requestContactsPermission just returns the current permission status. It is a single responsibility for that function and we can reuse it whenever we need it. Then inside contactsGetRequest we have business rules on how to react to each permission status. I would suggest to keep it as it is.

2020-10-15 12:42 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
> +    })
Nice advice, but it doesn't work the same.

I moved the sort function to a separate function 
const sortContacts = sort((a, b) => {
  if (a.user && b.user) {
    return a.fullName < b.fullName ? -1 : 1
  }

  if (!b.user) {
    return -1
  } else {
    return 1
  }
});

2020-10-15 12:45 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
> +      return { ...item, user: users[item.contactId] ? users[item.contactId].user : undefined }
Done, thanks

2020-10-15 12:47 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
> +        }
Done

2020-10-15 12:51 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsFollow.js
> +  try {
Done

2020-10-15 12:57 UTC, omelniz commented on src/store/ducks/contacts/queries.js
> +          url64p
That is a really good idea, but before entities are not persisted I can not fully implement it.

2020-10-15 12:58 UTC, omelniz commented on src/components/InviteFriends/index.js
> +    const navigateProfile = navigationActions.navigateProfile(navigation, { userId: user.userId })
Checked it, looks like it works well

2020-10-15 13:30 UTC, omelniz commented on __tests__/specs/store/ducks/contacts/saga/contactsGet.js
> +      const phone = parsePhoneNumberFromString(phoneStr, 'US')
Done

2020-10-16 10:03 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
> +        if (!phone.isValid()) {
remove it

2020-10-16 10:06 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
>  import Contacts from 'react-native-contacts'
getAll

2020-10-16 10:13 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsInvite.js
>        throw new Error('Invite supports only email and phone type')
throw

2020-10-17 15:21 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
>  import Contacts from 'react-native-contacts'
Done

2020-10-17 15:26 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
> +    phones: item.phones.reduce((acc, item) => {
Done

2020-10-17 15:26 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
> +        if (!phone.isValid()) {
Done

2020-10-17 15:28 UTC, omelniz commented on src/store/ducks/contacts/saga/contactsGet.js
>      }
Done

2020-10-19 13:28 UTC, merged